// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250307192727_TestData")]
    partial class TestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Product 1",
                            Price = 100m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Product 2",
                            Price = 200m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Product 3",
                            Price = 300m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Product 4",
                            Price = 400m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description 5",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Product 5",
                            Price = 500m,
                            Stock = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
